### ISSUE TITLE
Syncing remote entries only fetches images from Instagram user w/ access token 

### ISSUE THREAD

**Issue by bwlng** [weareboxhead/Craft-Instagram-Loader#1]
After adding a second user to my app's sandbox in the Instagram developer portal and including the second user’s ID in Instagram Loader's User Ids field, the plugin `syncWithRemote` action pulls only the user's instagrams that generated Access token.

In addition, adding a second user id duplicates instagrams from the account that generated the Access token (it appears the response from Instagram must return the feed of the user with the Access token because the imported entry data is the same, but the User Id field on the entry includes the second user's id).

Re-generating an access token using the second user‘s account allows their content to be imported, but then that user’s instagrams are imported twice instead of the originals user’s instagrams (but this verifies the sandboxed app can access both user’s instagrams).

Including only a single user id only imports instagrams from the account that generated the access token regardless of the user id input into the settings field. 

Is Instagram Loader still able to import multiple user’s photos or is this due to a change in Instagram’s API?

**Comment by mikevaux** [comment]
Hi Stephen,

Thanks so much for the thorough detailing of the problem you're facing.

The addition of the complex access token generation was due to an update / limitation in the way the API works, and it looks like this was not correctly integrated in Instagram Loader with requesting content from multiple user ids.

On line 68 of `instagramloader/services/InstagramLoader_EntriesService.php`, please can you try replacing

`$instagrams = $this->client->users()->getMedia();`
with
`$instagrams = $this->client->users()->getMedia($userId);`
?

[Looks like](http://elogram.readthedocs.io/en/stable/endpoints.html#getMedia) the id used by the `getMedia()` method defaults to 'self', which, if the access token is generated by the same user id as the content is being requested from, will work fine, but obviously will not work for multiple user ids.

Thanks!

**Comment by bwlng** [comment]
Thanks for the quick solution, Mike. This fixed my issue.

It does appear that in order to import instagrams from multiple users, the access token should be generated from the account that created the sandbox. Using an invitees code for other users in the sandbox throws an `API Not Allowed Error`.

Thanks so much!

**Comment by mikevaux** [comment]
Perfect, thanks Stephen!

Ah, really helpful to know - thanks. I've just fixed the initial issue in `master` so I'll close this one and open that as a separate issue. Should just be a case of updating the settings instructions language to make them clearer.
